#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/plinux/RosPacks/masterTank/devel_isolated/dwa_local_planner:/home/plinux/RosPacks/masterTank/devel_isolated/clear_costmap_recovery:/home/plinux/RosPacks/masterTank/devel_isolated/carrot_planner:/home/plinux/RosPacks/masterTank/devel_isolated/base_local_planner:/home/plinux/RosPacks/masterTank/devel_isolated/nav_core:/home/plinux/RosPacks/masterTank/devel_isolated/frontier_exploration:/home/plinux/RosPacks/masterTank/devel_isolated/costmap_2d:/home/plinux/RosPacks/masterTank/devel_isolated/voxel_grid:/home/plinux/RosPacks/masterTank/devel_isolated/hokuyo_node:/home/plinux/RosPacks/masterTank/devel_isolated/timestamp_tools:/home/plinux/RosPacks/masterTank/devel_isolated/robot_pose_ekf:/home/plinux/RosPacks/masterTank/devel_isolated/navigation:/home/plinux/RosPacks/masterTank/devel_isolated/master_tank_navigation:/home/plinux/RosPacks/masterTank/devel_isolated/amcl:/home/plinux/RosPacks/masterTank/devel_isolated/map_server:/home/plinux/RosPacks/masterTank/devel_isolated/fake_localization:/home/plinux/RosPacks/masterTank/devel_isolated/driver_common:/home/plinux/RosPacks/masterTank/devel_isolated/driver_base:/opt/ros/kinetic:/home/plinux/RosPacks/masterTank/devel_isolated/rtabmap"
export LD_LIBRARY_PATH="/home/plinux/RosPacks/masterTank/devel_isolated/dwa_local_planner/lib:/home/plinux/RosPacks/masterTank/devel_isolated/clear_costmap_recovery/lib:/home/plinux/RosPacks/masterTank/devel_isolated/carrot_planner/lib:/home/plinux/RosPacks/masterTank/devel_isolated/base_local_planner/lib:/home/plinux/RosPacks/masterTank/devel_isolated/nav_core/lib:/home/plinux/RosPacks/masterTank/devel_isolated/frontier_exploration/lib:/home/plinux/RosPacks/masterTank/devel_isolated/costmap_2d/lib:/home/plinux/RosPacks/masterTank/devel_isolated/voxel_grid/lib:/home/plinux/RosPacks/masterTank/devel_isolated/hokuyo_node/lib:/home/plinux/RosPacks/masterTank/devel_isolated/timestamp_tools/lib:/home/plinux/RosPacks/masterTank/devel_isolated/robot_pose_ekf/lib:/home/plinux/RosPacks/masterTank/devel_isolated/master_tank_navigation/lib:/home/plinux/RosPacks/masterTank/devel_isolated/amcl/lib:/home/plinux/RosPacks/masterTank/devel_isolated/map_server/lib:/home/plinux/RosPacks/masterTank/devel_isolated/fake_localization/lib:/home/plinux/RosPacks/masterTank/devel_isolated/driver_base/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/plinux/RosPacks/masterTank/devel_isolated/rtabmap/lib:/home/plinux/netbeans-8.1/cnd/bin/Linux-x86:/home/plinux/netbeans-8.1/cnd/bin/Linux-x86_64:/home/plinux/netbeans-8.1/bin/jre/jre/lib/amd64:/home/plinux/netbeans-8.1/bin/jre/jre/lib/i386"
export PATH="/opt/ros/kinetic/bin:/home/plinux/RosPacks/masterTank/devel_isolated/rtabmap/bin:/usr/bin:/home/plinux/bin:/home/plinux/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
export PKG_CONFIG_PATH="/home/plinux/RosPacks/masterTank/devel_isolated/dwa_local_planner/lib/pkgconfig:$PKG_CONFIG_PATH"
export PYTHONPATH="/home/plinux/RosPacks/masterTank/devel_isolated/dwa_local_planner/lib/python2.7/dist-packages:$PYTHONPATH"
export ROSLISP_PACKAGE_DIRECTORIES="/home/plinux/RosPacks/masterTank/devel_isolated/dwa_local_planner/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/plinux/RosPacks/masterTank/src/navigation/dwa_local_planner:$ROS_PACKAGE_PATH"