#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/plinux/RosPacks/masterTank/devel_isolated/timestamp_tools:/home/plinux/RosPacks/masterTank/devel_isolated/robot_pose_ekf:/home/plinux/RosPacks/masterTank/devel_isolated/navigation:/home/plinux/RosPacks/masterTank/devel_isolated/master_tank_navigation:/home/plinux/RosPacks/masterTank/devel_isolated/amcl:/home/plinux/RosPacks/masterTank/devel_isolated/map_server:/home/plinux/RosPacks/masterTank/devel_isolated/fake_localization:/home/plinux/RosPacks/masterTank/devel_isolated/driver_common:/home/plinux/RosPacks/masterTank/devel_isolated/driver_base:/home/plinux/RosPacks/urg_node/devel:/home/plinux/RosPacks/ork/devel:/home/plinux/RosPacks/moveit/devel:/home/plinux/RosPacks/usb_cam/devel:/opt/ros/kinetic:/home/plinux/RosPacks/masterTank/devel_isolated/rtabmap"
export LD_LIBRARY_PATH="/home/plinux/RosPacks/masterTank/devel_isolated/timestamp_tools/lib:/home/plinux/RosPacks/masterTank/devel_isolated/robot_pose_ekf/lib:/home/plinux/RosPacks/masterTank/devel_isolated/master_tank_navigation/lib:/home/plinux/RosPacks/masterTank/devel_isolated/amcl/lib:/home/plinux/RosPacks/masterTank/devel_isolated/map_server/lib:/home/plinux/RosPacks/masterTank/devel_isolated/fake_localization/lib:/home/plinux/RosPacks/masterTank/devel_isolated/driver_base/lib:/home/plinux/RosPacks/urg_node/devel/lib:/home/plinux/RosPacks/ork/devel/lib:/home/plinux/RosPacks/moveit/devel/lib:/home/plinux/RosPacks/usb_cam/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/plinux/RosPacks/masterTank/devel_isolated/rtabmap/lib:/home/plinux/RosPacks/masterTank/devel_isolated/rtabmap/lib/x86_64-linux-gnu:/home/plinux/RosPacks/ros_link/devel/lib"
export PATH="/home/plinux/RosPacks/ork/devel/bin:/opt/ros/kinetic/bin:/home/plinux/RosPacks/masterTank/devel_isolated/rtabmap/bin:/home/plinux/bin:/home/plinux/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
export PKG_CONFIG_PATH="/home/plinux/RosPacks/masterTank/devel_isolated/timestamp_tools/lib/pkgconfig:/home/plinux/RosPacks/masterTank/devel_isolated/robot_pose_ekf/lib/pkgconfig:/home/plinux/RosPacks/masterTank/devel_isolated/amcl/lib/pkgconfig:/home/plinux/RosPacks/masterTank/devel_isolated/map_server/lib/pkgconfig:/home/plinux/RosPacks/masterTank/devel_isolated/fake_localization/lib/pkgconfig:/home/plinux/RosPacks/masterTank/devel_isolated/driver_base/lib/pkgconfig:/home/plinux/RosPacks/urg_node/devel/lib/pkgconfig:/home/plinux/RosPacks/ork/devel/lib/pkgconfig:/home/plinux/RosPacks/moveit/devel/lib/pkgconfig:/home/plinux/RosPacks/usb_cam/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig:/home/plinux/RosPacks/masterTank/devel_isolated/rtabmap/lib/pkgconfig:/home/plinux/RosPacks/masterTank/devel_isolated/rtabmap/lib/x86_64-linux-gnu/pkgconfig:/home/plinux/RosPacks/ros_link/devel/lib/pkgconfig"
export PYTHONPATH="/home/plinux/RosPacks/masterTank/devel_isolated/robot_pose_ekf/lib/python2.7/dist-packages:/home/plinux/RosPacks/masterTank/devel_isolated/amcl/lib/python2.7/dist-packages:/home/plinux/RosPacks/masterTank/devel_isolated/driver_base/lib/python2.7/dist-packages:/home/plinux/RosPacks/urg_node/devel/lib/python2.7/dist-packages:/home/plinux/RosPacks/ork/devel/lib/python2.7/dist-packages:/home/plinux/RosPacks/moveit/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages:/home/plinux/RosPacks/masterTank/devel_isolated/rtabmap/lib/python2.7/dist-packages"
export ROSLISP_PACKAGE_DIRECTORIES="/home/plinux/RosPacks/masterTank/devel_isolated/timestamp_tools/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/plinux/RosPacks/masterTank/src/driver_common/timestamp_tools:$ROS_PACKAGE_PATH"