# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/Info.msg;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/KeyPoint.msg;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/MapData.msg;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/MapGraph.msg;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/NodeData.msg;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/Link.msg;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/OdomInfo.msg;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/Point2f.msg;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/Point3f.msg;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/Goal.msg;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/RGBDImage.msg;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg/UserData.msg"
services_str = "/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/srv/GetMap.srv;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/srv/ListLabels.srv;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/srv/PublishMap.srv;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/srv/ResetPose.srv;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/srv/SetGoal.srv;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/srv/SetLabel.srv"
pkg_name = "rtabmap_ros"
dependencies_str = "std_msgs;geometry_msgs;sensor_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "rtabmap_ros;/home/thor/Dropbox/DTU_5_sem/Ros/masterTank/src/rtabmap_ros/src/rtabmap_ros/msg;std_msgs;/opt/ros/kinetic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/kinetic/share/geometry_msgs/cmake/../msg;sensor_msgs;/opt/ros/kinetic/share/sensor_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
